version: '3.8'
services:
    agrisk-ui:
        container_name: agrisk-app
        build:
            context: .
            dockerfile: Dockerfile

        ports: 
            - 3001:3001

        environment:
            - CHOKIDAR_USEPOLLING=true

        stdin_open: true

        volumes: 
            - './:/app'
            - '/app/node_modules'