version: '3.8'

services:

  agrisk-ui:
    container_name: agrisk
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment: 
      - REACT_APP_GOOGLE_API=AIzaSyC7QJNDGuQ94FH1G3kUTD2HDfcigYPkcW4
    ports:
      - '1337:80'